spring:
  profiles:
    active: prod
  # DATASOURCE
  datasource:
    hikari:
      primary:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_URL}/gream
        username: ${DB_ID}
        password: ${DB_PASSWORD}
  #      secondary:
  #        driver-class-name: com.mysql.cj.jdbc.Driver
  #        jdbc-url: jdbc:mysql://${DB_READ_ONLY_URL}/gream
  #        username: ${DB_ID}
  #        password: ${DB_PASSWORD}
  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        auto_quote_keyword: true # 예약어 사용가능
        globally_quoted_identifiers: true # 예약어 사용가능
        show_sql: true # sql 로깅
        # generate_statistics: true # 쿼리수행 통계
        format_sql: true # SQL문 정렬하여 출력
        highlight_sql: true # SQL문 색 부여
  # REDIS
  data:
    redis:
      host: ${REDIS_URL}
      port: 6379
      repositories:
        enabled: false
# JWT
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

# s3
cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    stack.auto: false
    region.static: ${REGION}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_ACCESS_KEY}

# OAuth2
oauth2:
  kakao:
    token-uri: ${KAKAO_TOKEN_URI}
    user-info-uri: ${KAKAO_USER_INFO_URI}
    client-id: ${KAKAO_CLIENT_ID}
    redirect-url: ${KAKAO_REDIRECT_URL}

# Actuator 설정
management:
  endpoints:
    prometheus: # 활성화를 원하는 엔드포인트의 id
      enabled: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# tomcat was 메트릭으로 변경
server:
  tomcat:
    mbeanregistry:
      enabled: true